import { Work, Order, PlagiarismCheck, Transaction, User } from '@/types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user_student_1',
    fullName: 'Azizbek Rahimov',
    phone: '+998 90 123 45 67',
    email: 'azizbek@example.com',
    role: 'STUDENT',
    balance: 0,
    telegramUsername: 'azizbek_dev',
    createdAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'user_author_1',
    fullName: 'Dr. Shahzodbek Mahmudov',
    phone: '+998 93 987 65 43',
    email: 'shahzod@expert.uz',
    role: 'AUTHOR',
    balance: 0,
    telegramUsername: 'shahzod_author',
    createdAt: '2026-08-15T08:30:00Z',
  },
  {
    id: 'user_admin_1',
    fullName: 'Admin Boshqaruvchi',
    phone: '+998 99 000 11 22',
    email: 'admin@cosapl.uz',
    role: 'ADMIN',
    balance: 0,
    telegramUsername: 'cosapl_admin',
    createdAt: '2026-08-01T00:00:00Z',
  },
];

export const INITIAL_WORKS: Work[] = [
  {
    id: 'work_1',
    title: "Sun'iy intellekt texnologiyalarining bank tizimida kredit risklarini baholashdagi samaradorligi",
    subject: 'Axborot texnologiyalari va Moliya',
    category: 'KURS_ISHI',
    description: "Mazkur kurs ishida bank tizimlarida Machine Learning algoritmlari (Scoring tizimlari, Decision Trees va Neyron to'rlari) yordamida mijozlarning kredit qobiliyati va risklarini avtomatlashtirilgan baholash modellari tahlil qilingan. Ish to'liq O'zbekiston banklari amaliyoti asosida yoritilgan.",
    tableOfContents: [
      "KIRISH",
      "I BOB. BANK TIZIMIDA KREDIT RISKLARINI BAHOLASHNING NAZARIY VA USLUBIY ASOSLARI",
      "1.1. Kredit risklari tushunchasi va an'anaviy skoring modellari",
      "1.2. Sun'iy intellekt va Machine Learning algoritmlarining bank amaliyotiga tatbiqi",
      "II BOB. TIJORAT BANKLARIDA SUN'IY INTELLEKT ASOSIDA KREDIT SKORINGINI TAHLIL QILISH",
      "2.1. O'zbekiston tijorat banklarida kredit risklarini boshqarishning joriy holati",
      "2.2. Python tilida Random Forest va XGBoost algoritmlari asosida risklarni modellashtirish",
      "III BOB. KREDIT RISKLARINI KAMAYTIRISHDA SUN'IY INTELLEKTDAN FOYDALANISHNI TAKOMILLASHTIRISH",
      "3.1. Zamonaviy FinTech tizimlari bilan integratsiyalash istiqbollari",
      "XULOSA VA TAKLIFLAR",
      "FOYDALANILGAN ADABIYOTLAR RO'YXATI"
    ],
    introductionPreview: "Mavzuning dolzarbligi: Zamonaviy iqtisodiy sharoitda tijorat banklarining barqaror faoliyat yuritishi to'g'ridan-to'g'ri kredit portfeli sifatiga va risklarni to'g'ri baholashga bog'liqdir. An'anaviy tahlil usullari katta hajmdagi noaniq va tez o'zgaruvchan ma'lumotlarni qayta ishlashda yetarli darajada tezkorlikni ta'minlay olmaydi...",
    pagesCount: 38,
    language: 'UZ',
    price: 45000,
    originalFileUrl: '/uploads/sample_kurs_ishi_1.docx',
    previewFileUrl: '/uploads/sample_kurs_ishi_1_preview.pdf',
    authorId: 'user_author_1',
    authorName: 'Dr. Shahzodbek Mahmudov',
    status: 'APPROVED',
    salesCount: 14,
    uniquenessPercent: 82,
    rating: 4.9,
    downloadsCount: 18,
    createdAt: '2026-08-21T12:00:00Z',
  },
  {
    id: 'work_2',
    title: "O'zbekistonda elektron tijorat (E-commerce) bozorini rivojlantirishning strategik yo'nalishlari",
    subject: 'Iqtisodiyot va Marketing',
    category: 'MDI',
    description: "Malakaviy bitiruv ishi (MDI). O'zbekistondagi milliy marketpleyslar (Uzum, Zoodmall, Olx) tahlili, logistika zanjirlari, to'lov tizimlari va raqamli marketing vositalarining bozor o'sishiga ta'siri batafsil hisob-kitoblar bilan keltirilgan.",
    tableOfContents: [
      "KIRISH",
      "1-BOB. ELEKTRON TIJORATNING NAZARIY VA HUQUQIY ASOSLARI",
      "2-BOB. O'ZBEKISTONDA ELEKTRON SAVDO BOZORINING ZAMONAVIY HOLATI VA DINAMIKASI",
      "3-BOB. E-COMMERCE SOHASINI RIVOJLANTIRISH VA EKSPORT IMKONIYATLARINI OSHIRISH ISTIQBOLLARI",
      "XULOSA",
      "ILOVALAR VA ADABIYOTLAR"
    ],
    introductionPreview: "Bugungi globallashuv va raqamli transformatsiya davrida elektron tijorat jahon iqtisodiyotining drayverlaridan biriga aylanmoqda. O'zbekiston Respublikasi Prezidentining 'Raqamli O'zbekiston — 2030' strategiyasida ham savdo-sotiqni raqamlashtirish bo'yicha ustuvor vazifalar belgilab berilgan...",
    pagesCount: 65,
    language: 'UZ',
    price: 90000,
    originalFileUrl: '/uploads/sample_mdi_1.docx',
    authorId: 'user_author_1',
    authorName: 'Dr. Shahzodbek Mahmudov',
    status: 'APPROVED',
    salesCount: 8,
    uniquenessPercent: 88,
    rating: 5.0,
    downloadsCount: 10,
    createdAt: '2026-08-19T09:15:00Z',
  },
  {
    id: 'work_3',
    title: "Boshlang'ich sinf o'quvchilarida mantiqiy fikrlashni shakllantirishda interaktiv metodlar",
    subject: 'Pedagogika va Psixologiya',
    category: 'KURS_ISHI',
    description: "Pedagogika yo'nalishi talabalari uchun tayyor kurs ishi. Boshlang'ich ta'limda zamonaviy STEAM texnologiyalari, didaktik o'yinlar va mantiqiy mashqlar to'plamini o'z ichiga oladi. Dars ishlanmasi va taqdimot ilova qilingan.",
    tableOfContents: [
      "KIRISH",
      "I BOB. BOSHLANG'ICH SINF O'QUVCHILARIDA MANTIQIY TAFAKKURNI RIVOJLANTIRISHNING PSIXOLOGIK-PEDAGOGIK XUSUSIYATLARI",
      "II BOB. DARSLARDA INTERAKTIV METOD VA O'YINLARDAN FOYDALANISH METODIKASI",
      "XULOSA VA TAVSIYALAR",
      "ADABIYOTLAR RO'YXATI",
      "ILOVA (1 SOATLIK DARS ISHLANMASI)"
    ],
    introductionPreview: "Ta'lim tizimini tubdan isloh qilish davrida yosh avlodni mustaqil, erkin va tanqidiy fikrlaydigan shaxs qilib tarbiyalash muhim vazifa hisoblanadi. Ayniqsa, boshlang'ich sinf yoshidagi bolalarda analiz, sintez va mantiqiy xulosalar chiqarish qobiliyatini shakllantirish o'ta dolzarbdir...",
    pagesCount: 32,
    language: 'UZ',
    price: 35000,
    originalFileUrl: '/uploads/sample_pedagogika_1.docx',
    authorId: 'user_author_1',
    authorName: 'Dr. Shahzodbek Mahmudov',
    status: 'APPROVED',
    salesCount: 22,
    uniquenessPercent: 79,
    rating: 4.8,
    downloadsCount: 25,
    createdAt: '2026-08-18T14:40:00Z',
  },
  {
    id: 'work_4',
    title: "Yangi O'zbekiston Ma'muriy Huquqi: Islohotlar va Raqamlashtirish",
    subject: 'Huquqshunoslik va Davlat Boshqaruvi',
    category: 'REFERAT',
    description: "Davlat xizmatlarini ko'rsatishda ma'muriy tartib-taomillarning raqamlashtirilishi, My.gov.uz va Yagona darcha tamoyillarining huquqiy asoslari tahlili. Yangi qonunchilik hujjatlari bilan boyitilgan.",
    tableOfContents: [
      "1. Ma'muriy islohotlarning mazmuni va zarurati",
      "2. Davlat boshqaruvida raqamli texnologiyalarning huquqiy maqomi",
      "3. Fuqarolar huquqlarini himoya qilishda ma'muriy sudlar o'rni",
      "Xulosa va Foydalanilgan manbalar"
    ],
    introductionPreview: "Ma'muriy huquq sohasidagi keng ko'lamli islohotlar inson qadrini yuksaltirish va davlat organlarining fuqarolarga xizmat qilishini ta'minlashga yo'naltirilgan. Ushbu referatda so'nggi qabul qilingan kodeks va qarorlar tahlil qilinadi...",
    pagesCount: 18,
    language: 'UZ',
    price: 20000,
    originalFileUrl: '/uploads/sample_huquq_referat.docx',
    authorId: 'user_author_1',
    authorName: 'Dr. Shahzodbek Mahmudov',
    status: 'APPROVED',
    salesCount: 31,
    uniquenessPercent: 85,
    rating: 4.7,
    downloadsCount: 35,
    createdAt: '2026-08-15T11:20:00Z',
  },
  {
    id: 'work_5',
    title: "Yurak-qon tomir kasalliklarini erta aniqlashda zamonaviy biomarkerlar",
    subject: 'Tibbiyot va Farmatsevtika',
    category: 'TAQDIMOT',
    description: "Tibbiyot oliygohlari talabalari uchun 25 slayddan iborat chiroyli va animatsiyalarga ega professional PowerPoint taqdimoti (.pptx). Troponin, BNP, hs-CRP kabi yangi biomarkerlar diagnostikasi yoritilgan.",
    tableOfContents: [
      "Slayd 1-3: Kirish va epidemiologiya",
      "Slayd 4-10: An'anaviy va yangi kardiomarkerlar",
      "Slayd 11-18: Erta tashxislash algoritmlari va klinik holatlar",
      "Slayd 19-25: Xulosa va tavsiyalar"
    ],
    introductionPreview: "Kardiologiya amaliyotida erta tashxis kasallik asoratlarini kamaytirishning asosiy omilidir. Taqdimotda yuqori sezuvchanlikka ega biomarkerlarning klinik qiymati infografikalar bilan tushuntirilgan...",
    pagesCount: 25,
    language: 'UZ',
    price: 25000,
    originalFileUrl: '/uploads/sample_tibbiyot_pres.pptx',
    authorId: 'user_author_1',
    authorName: 'Dr. Shahzodbek Mahmudov',
    status: 'APPROVED',
    salesCount: 19,
    uniquenessPercent: 92,
    rating: 5.0,
    downloadsCount: 20,
    createdAt: '2026-08-14T16:00:00Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord_101',
    orderType: 'INDIVIDUAL',
    studentId: 'user_student_1',
    studentName: 'Azizbek Rahimov',
    studentPhone: '+998 90 123 45 67',
    assignedAuthorId: 'user_author_1',
    assignedAuthorName: 'Dr. Shahzodbek Mahmudov',
    subject: 'Axborot texnologiyalari',
    topic: "Kiberxavfsizlikda zero-trust (nol ishonch) arxitekturasini loyihalash",
    requirements: "30-35 bet bo'lishi kerak. Kirish, 3 ta bob, xulosa va adabiyotlar. Antiplagiat kamida 75% bo'lsin. Metodik qo'llanma ilova qilingan.",
    deadline: '2026-09-10',
    pageCount: 35,
    language: 'UZ',
    attachments: [
      { name: 'Metodik_qollanma_TATU_2026.pdf', url: '/uploads/metodika.pdf', size: '2.4 MB' }
    ],
    freePlanStatus: 'COMPLETED',
    freePlanCompletedAt: '2026-08-22T15:00:00Z',
    preparedPlanText: "1. Kirish\n2. I Bob. Zero-Trust xavfsizlik modelining konseptual asoslari\n3. II Bob. Korporativ tarmoqlarda Zero-Trust vositalarini joriy etish tahlili\n4. III Bob. Bulutli muhitda autentifikatsiya va monitoring samaradorligini oshirish\n5. Xulosa va Foydalanilgan adabiyotlar",
    agreedPrice: 120000,
    status: 'IN_PROGRESS',
    createdAt: '2026-08-22T10:00:00Z',
  }
];

export const INITIAL_MESSAGES: Record<string, any[]> = {
  'ord_101': [
    {
      id: 'msg_1',
      orderId: 'ord_101',
      senderId: 'user_student_1',
      senderName: 'Azizbek Rahimov',
      senderRole: 'STUDENT',
      text: "Assalomu alaykum! Mavzu bo'yicha metodik qo'llanmani biriktirdim. Rejani ko'rib bera olasizmi?",
      timestamp: '2026-08-22T10:05:00Z',
    },
    {
      id: 'msg_2',
      orderId: 'ord_101',
      senderId: 'user_author_1',
      senderName: 'Dr. Shahzodbek Mahmudov',
      senderRole: 'AUTHOR',
      text: "Vaalaykum assalom Azizbek! Metodikani o'rganib chiqdim. 24 soat ichida kafedra talablariga mos bepul namunaviy rejani tayyorlab yubordim. Tekshirib ko'ring.",
      timestamp: '2026-08-22T15:05:00Z',
    }
  ]
};

export const INITIAL_PLAGIARISM_CHECKS: PlagiarismCheck[] = [
  {
    id: 'plg_201',
    userId: 'user_student_1',
    userName: 'Azizbek Rahimov',
    userPhone: '+998 90 123 45 67',
    documentUrl: '/uploads/azizbek_tatu_kurs_ishi.docx',
    fileName: 'Kiberxavfsizlik_kurs_ishi_Azizbek.docx',
    subject: 'Axborot xavfsizligi',
    topic: 'Kiberxavfsizlikda zamonaviy shifrlash algoritmlari',
    price: 25000,
    isPaid: true,
    status: 'COMPLETED',
    uniquenessPercent: 86.4,
    fullReportPdfUrl: 'https://antiplag.uz/report/EM2026-8941',
    certificatePdfUrl: 'https://antiplag.uz/cert/EM2026-8941',
    certificateCode: 'AP-2026-8941',
    completedAt: '2026-08-23T16:30:00Z',
    createdAt: '2026-08-23T14:10:00Z',
  }
];

export const INITIAL_TRANSACTIONS: Transaction[] = [];
